# Generated by Django 5.1.3 on 2024-11-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0003_alter_exchangerate_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
    ]
